### ISSUE TITLE
Invalid OS commands to delete temp files

### ISSUE THREAD

**Issue by wr3nch0x1** [stevenaldinger/Evil-AP-golang#1]
```[*] Moving Meterpreter Payload to Normal/Legitimate APK
[+] Moved Successfully!

[>] Adding Permissions in androidManifest.xml
[>] Injected Successfully!

[>] Finding smali launcher : MainActivity.smali
rm: cannot remove 'ramp': No such file or directory
rm: cannot remove 'result': No such file or directory
rm: cannot remove 'twelv.txt': No such file or directory
rm: cannot remove '2': No such file or directory
grep: Invalid range end
cat: result: No such file or directory
Traceback (most recent call last):
  File "/opt/Infector/binder.py", line 359, in <module>
    main()
  File "/opt/Infector/binder.py", line 358, in main
    pay_type()
  File "/opt/Infector/binder.py", line 282, in pay_type
    line = subprocess.check_output("cat result",shell=True)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cat result' returned non-zero exit status 1.```

**Comment by stevenaldinger** [comment]
are you sure that output is from this repo? this is a golang repo (unmaintained btw, just an example) and that's a python stack trace.

**Comment by wr3nch0x1** [comment]
I'm sorry i posted on wrong repo. Looks like i need a coffee break. Haha! Cheers
